### ISSUE TITLE
Unexpected formatting with default intel.console()

### ISSUE THREAD

**Issue by mfn** [seanmonstar/intel#36]
Using node v0.12.3 and intel 1.0.0

Consider this small example in the directory `testing_intel` named `test_intel.js`:

``` JS
var intel = require('intel');
intel.console();

console.error('1 - error');
console.info('2 - info');
console.log('3 - log');
console.trace('4 - trace');
console.warn('5 - warn');
console.debug('6 - debug');
```

The output contains unexpected `.DEBUG` formattings for level `ERROR` and `WARN`:

```
$ node test_intel.js
testing_intel.node_modules.intel.handlers.stream.DEBUG: testing_intel.test_intel.ERROR: 1 - error

testing_intel.test_intel.INFO: 2 - info
testing_intel.test_intel.DEBUG: 3 - log
testing_intel.test_intel.TRACE: 4 - trace
    at deliver (/home/vagrant/tmp/testing_intel/node_modules/intel/lib/console.js:244:17)
    at Console.alias (/home/vagrant/tmp/testing_intel/node_modules/intel/lib/console.js:270:7)
    at Object.<anonymous> (/home/vagrant/tmp/testing_intel/test_intel.js:7:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
testing_intel.node_modules.intel.handlers.stream.DEBUG: testing_intel.test_intel.WARN: 5 - warn

testing_intel.test_intel.DEBUG: 6 - debug
```

Specifically, I would expect these two lines:

```
testing_intel.node_modules.intel.handlers.stream.DEBUG: testing_intel.test_intel.ERROR: 1 - error

testing_intel.node_modules.intel.handlers.stream.DEBUG: testing_intel.test_intel.WARN: 5 - warn

```

to look like the following and do not contain an extra empty line:

```
testing_intel.test_intel.ERROR: 1 - error
testing_intel.test_intel.WARN: 5 - warn
```

Is my assumption wrong?

**Comment by mfn** [comment]
Another indication something isn't working properly: consider this file in `testing_intel/test_intel.js`:
```JS
var intel = require('intel');
var config = {
  handlers: {
    console: {
      class: intel.handlers.Console
    }
  },
  loggers: {
    'testing_intel.test_intel': {
      handlers: ['console']
    }
  }
};
intel.config(config);
intel.console();

console.error('1 - error');
console.info('2 - info');
console.log('3 - log');
console.trace('4 - trace');
console.warn('5 - warn');
console.debug('6 - debug');
```
Output:
```
$ node test_intel.js
2 - info
3 - log
4 - trace
    at deliver (/vagrant/testing_intel/node_modules/intel/lib/console.js:245:17)
    at Console.alias (/vagrant/testing_intel/node_modules/intel/lib/console.js:271:7)
    at Object.<anonymous> (/vagrant/testing_intel/test_intel.js:20:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
6 - debug
```
As can bee seen, `error` and `warn` level are unexpectedly missing.

**Comment by mfn** [comment]
I've figured so far it relates to handling of `stderr` output. Both `lib/console.js` and `lib/handlers/console.js` *do something* with `process.stderr`.

From `lib/console.js`:
```JS
function overrideConsole() {
  // ...
  process.stderr.write = function write(str) {
    deliver('stderr', [str]);
    return true;
  };
}
```
and in `lib/handlers/console.js`:
```JS
ConsoleHandler.prototype.emit = function consoleEmit(record) {
  var handler = (record.level >= LEVELS.WARN) ? this._err : this._out;
  handler.emit(record);
};
```
whereas `this._err` is a stream handler using `process.stderr`.

I think what happens is that levels >= WARN get through `lib/handlers/console.js` to `process.stderr` and since `process.stderr.write()` is overwritten in `lib/console.js` it gets emitted as a `DEBUG` level first and that's why we're seeing this:
`testing_intel.node_modules.intel.handlers.stream.DEBUG: testing_intel.test_intel.ERROR: 1 - error`

I was able to work this around with a custom `consoleStdout` handler:
```JS
const util = require('util');
const intel = require('intel');

function ConsoleStdoutHandler(options) {
  options = options || {};
  options.stream = process.stdout;
  this._out = new intel.handlers.Stream(options);
  intel.Handler.call(this, options);
}

util.inherits(ConsoleStdoutHandler, intel.Handler);

ConsoleStdoutHandler.prototype.emit = function consoleStdoutEmit(record) {
  this._out.emit(record);
};

ConsoleStdoutHandler.prototype.setFormatter = function setFormatter(formatter) {
  intel.Handler.prototype.setFormatter.call(this, formatter);
  this._out.setFormatter(formatter);
};

module.exports = ConsoleStdoutHandler;
```

**Comment by seanmonstar** [comment]
We still use nodejs 0.10.x ourselves, I wonder if the `console.js` module in node changed a bit of it's structure (I use hacky stacktraces to override the console).

------

Separately, if you can help it, in your application, use the actual intel loggers, instead of `console.log`. It's much faster, since the `console.log` have to generate a stacktrace every time. Plus, the intel loggers intelligently become noops for all levels that you're not listening for (so all my debug/verbose logs in production basically call `function noop() {}`).

Also, as explained in [these](http://seanmonstar.com/post/72010941112/intel-0-4) [articles](http://seanmonstar.com/post/76370146228/intel-v0-5), I've moved away from suggesting using `console.log` everywhere, and use something like debug/dbug.

**Comment by mfn** [comment]
Also not using this anymore 🤷‍♀️ => closing
