### ISSUE TITLE
Writing logs related to some script in two different files independently

### ISSUE THREAD

**Issue by nkovalenko-sc** [seanmonstar/intel#52]
Hi! I faced the following problem with logger: 
I have global application logger and I have few jobs, which should call some function from some script every hour. Two of that jobs run different functions from the same script.
I have to log operations for each job to the separate file. All jobs are starting at the same time (not sequentially). But I'm getting mixed logs in files which logs the same script. 

My abstract implementation:

logger.js ('init' function loads on server startup)
----------------------------------------------------
```
// logScriptPath is 'scripts.testScript' in this case
function initJobLogFile(jobName, logScriptPath) {
  return new Promise((resolve, reject) => {
    let logger = intel.getLogger(logScriptPath);
    mkdirp(logFilePath, err => {
        logger.addHandler(
          new intel.handlers.File({
            file: `./testPath/${jobName}/logFileName.log`,
            formatter: new intel.Formatter({
              format: '%(date)s (%(levelname)s) [%(name)s] %(message)s'
            })
          })
        );
        resolve(logger);
  });
}

function removeAllHandlers(logScriptPath) {
  let logger = intel.getLogger(logScriptPath);
  logger.removeAllHandlers();
}

function init() {
  let loggingConfig = applicationConfigurationService.getLoggingConfig();
  let logfilePath = loggingConfig.filePath;
  return new Promise(resolve => {
        intel.config(loggingConfig);
        intel.console();
        intel.addHandler(
          new intel.handlers.Stream({
            stream: rotating({
              file: logfilePath,
              size: '200mb',
             keep: 20
            }),
            level: intel.ALL,
            formatter: new intel.Formatter({
              format: '%(date)s (%(levelname)s) [%(name)s] %(message)s'
            })
          })
        );
        resolve();
  });
}

export default {
  init: init,
  initJobLogFile: initJobLogFile,
  removeAllHandlers: removeAllHandlers
}
```

scripts/testScript.js
-------------------------------------------
```
function job1() {
   console.info('Job 1 function started');
}
function job2() {
   console.info('Job 2 function started');
}
export default {
  job1: job1,
  job2: job2
}
```

Job calling is the following:
------------------------------------------
```
// initialization logger to write logs from script 'scripts.testScript' to the separate file
// this code is calling in forEach loop which iterates through few jobs
logger.initJobLogFile(name, 'scripts.testScript').then(()=> {
      // calling job function, task can be one of functions job1 and job2
      return job.task().then(() => {
        // closing separate file logger
        return logger.removeAllHandlers(job.logScriptPath);
      });
});
```

As a result I have two files: job1.log and job2.log
job1.log contains:
```
Job 1 function started
Job 2 function started
```

job2.log contains:
```
Job 2 function started
```

If add much more logs, job2 will contain some part of job1's logs (it's because job1 starts little bit earlier).

May be you can suggest me how can I resolve that problem?
Thank you.

**Comment by seanmonstar** [comment]
Ah, it's probably related to the usage of `console.info()`. When used with `intel.console()`, logging through the `console` will determine the name of the logger based on the path and filename of module that used the `console`. So, in your case, both loggers will have a name of `scripts.testScript`, so they both get passed to the handlers of that logger. Since your log setup gets the logger by the script name, and adds a handler, the second jobs logs get sent to all the handlers of that logger.

You have a couple of different ways to solve this.

- Separate your jobs into different files. Doing this means the `console` will generate different names for the log operations.
- Add a [`intel.Filter`](http://seanmonstar.github.io/intel/#filters) to the loggers or the specific handlers, which can filter messages by log name, by message contents via regex, or by a custom function.

**Comment by nkovalenko-sc** [comment]
Thank you. It's fine, but I improved my code:
I started passing job name to script when running task ```job.task(jobName)```.
Added filter to ```function initJobLogFile```
```
logger.addFilter(new intel.Filter(
          record => {
            let message = '';
            if (record.args && record.args.length > 0) {
              record.args.forEach((arg, index) => {
                message += `${index && ' ' || ''}${arg}`;
              });
            }
            return message.indexOf(` (${jobName} job)`) >= 0;
          })
);
```
and added string ``` (${jobName} job)``` to each ```console.info``` function in script.

As a result I have two files: job1.log and job2.log

job1.log contains:
'Job 1 function started (Job 1 job)'

job2.log contains nothing.

If add much more logs, job1 will contain just firs log message 'Job 1 function started (Job 1 job)', job2 will still contain nothing.

**Comment by nkovalenko-sc** [comment]
I can assume first job adds some handlers, then second job adds to or overwrites handlers added by first job. I can't place code in a separate scripts, because there are common logic.
Do you know some workarounds?

**Comment by nkovalenko-sc** [comment]
Is it possible to create independent intel logger for each job? I tried, but my tries has failed.

**Comment by seanmonstar** [comment]
You can create specific loggers either by name, using intel.getLogger in the tasks file, or if you wish to use console, you need them in separate files. 

If using the same Logger, you could put the Filter on the Handler, to only let certain logs go to that specific file.

**Comment by nkovalenko-sc** [comment]
"If using the same Logger, you could put the Filter on the Handler, to only let certain logs go to that specific file." - what does it mean?
I have a situation when first job starts to work, gets logger by script path (i.e. 'scripts.testScript'), adds some filter by regexp, writes out filtered logs to log file.
Second job starts to work, gets logger by script path (i.e. 'scripts.testScript'), adds some filter by regexp. 
Result: logger for script 'scripts.testScript' has 2 filters, log file for the second job is empty, because log messages can't go through 2 different filters, and logs are no longer being written to the first log file for the same reason.

**Comment by seanmonstar** [comment]
Here's what I mean:

```js
// logScriptPath is 'scripts.testScript' in this case
function initJobLogFile(jobName, logScriptPath) {
  return new Promise((resolve, reject) => {
    let logger = intel.getLogger(logScriptPath);
    mkdirp(logFilePath, err => {
        let handler = new intel.handlers.File({
            file: `./testPath/${jobName}/logFileName.log`,
            formatter: new intel.Formatter({
              format: '%(date)s (%(levelname)s) [%(name)s] %(message)s'
            })
        );
        // this new File handler should filter out all messages
        // that aren't from `jobName`
        handler.addFilter(new intel.Filter(new RegExp('^' + jobName)));
        logger.addHandler(handler);
        resolve(logger);
  });
}
```

**Comment by nkovalenko-sc** [comment]
Oh you're god, bro. Thank you a lot :)
